### PR TITLE
Feature/storybook dropdown

### PR DESCRIPTION
**Pull request by henrylatham**
@tomothespian 

There are some errors in here I was unable to solve, but I've tried to use the same structure you have setup in Menu (with Props and State) where possible

### CODE REVIEW

**Comment by henrylatham** [comment]
@tomothespian Let me know if this needs any changes - it's using `state` more than `props` so we can update the UI and store the selected option

**Comment by tomothespian** [comment]
@henrylatham that is not good. We are using states just for inner changes. Soo menu items should be declared on the very top component (container) as props.

Please change that. I will leave this one unmerged

**Comment by henrylatham** [comment]
@tomothespian Could you add comments in the code or we review tomorrow? I'm not sure how to improve this

**Comment by tomothespian** [comment]
@henrylatham it is better to review together.

**Comment by henrylatham** [comment]
@tomothespian I tried to solve this over the weekend, but wasn't able to! I pushed my most recent version with `no-verify`, so could you make fixes and push live in the next few days? I think it will only take you half an hour or so, as it's just an issue with applying `state` to a specific dropdown item

I'd like to start testing the prototype (ideally in Storybook) by Wednesday, so before then would be great (let me know if you won't have time though?)

**Comment by tomothespian** [comment]
@henrylatham please take a look at the latest changes!

**Pull request merged**
