### PR TITLE
Feature/storybook menu

### PR DESCRIPTION
**Pull request by henrylatham**
@tomothespian A couple of notes for this PR:

1. You'll see when you run `Yarn prettier:format` there are quite a few warnings that I am not sure how to solve. If you think they are worth solving, then feel free to do so. We need to be careful with how we use our time though, so I would suggest only solving things that we will use in future (e.g. Mailchimp will only be used during our Beta programme, so no point correcting those warnings)

2. Menu: 

a. Currently when a menu item is clicked on the Menu story, all the menu items change to `itemActive = true`. Functionality should be that only the item clicked becomes `itemActive = true`

b. Note that the icon event is separate from the event when the text is clicked (e.g. 'Vision'). This is deliberate, as I suspect we will trigger different events with different icons here (e.g. 'arrow;' would maybe show a dropdown menu, 'add' would add the item to your profile)

3. Let me know if you are happy with this approach to me submitting storybook PRs? I think it's best to work on all the individual elements & small blocks first, then I'll build pages (such as authentication and the main app page)

### CODE REVIEW

**Comment by tomothespian** [comment]
@henrylatham 
1. Prettier - when I run prettier everything is clean. To automatically let prettier to format code just enter command `yarn prettier:format` and command will do rest. it is really important to keep code clean even we wouldn't use some things in the future. If something fails we will be 100% sure that is not some dummy code issue in current build!

2. I made code fix regarding to menu items active / inactive state. Please take a look

P.S. approach is ok. 
One small thing as a suggestion. If you have a menu with menu items as story then you don't need to create separated stories for each menu item state e.g. Menu Item - active. You can do all together inside the first story `Menu: Full`. Put one item to disable state and other items will automatically become active / inactive on click as is defined inside the component. Also `Menu` component, to be reusable, should accept menu items. So please remove menu items from Menu component and pass from the parent component. Same is in the storybook, define menu items and just pass to `<Menu items={menuItems} />`
Also, write more descriptive commit messages about what you did. If we have same message for multiple commits we will be lost in PR. So each message should describe exactly what you did in that commit

**Comment by henrylatham** [comment]
1. I ran prettier and `lint` last time, but think our setup must be different. I'm still getting these warnings:

```

  src/components/blocks/Hero/Hero.js:18:16
  ⚠   18:16  onSubscribe PropType is defined but prop is never used                  react/no-unused-prop-types
  ⚠   21:23  onSubscribe is missing in props validation                              react/prop-types
  ⚠   26:5   Expected an assignment or function call and instead saw an expression.  no-unused-expressions
  ⚠   36:14  Arrow function should not return assignment.                            no-return-assign
  ⚠  103:21  Dangerous property dangerouslySetInnerHTML found                        react/no-danger

  src/components/blocks/Menu/Menu.js:80:19
  ⚠   80:19  JSX props should not use .bind()                                        react/jsx-no-bind

```

2. Approach: Ok, makes sense. I've removed unnecessary stories. For commit messages, is there away to create paragraphs? Rather than just one long line of text? Also, this is a really good point - I am fairly sure we will be going back and forth to old/new commits over the coming months, so let's put in a big effort to make every commit crystal clear

**Comment by henrylatham** [comment]
@tomothespian Otherwise, PR ready to merge. I just removed some commented code and the MenuItem stories

**Comment by tomothespian** [comment]
@henrylatham 
1. You are getting errors because you have valid issues in code. I will fix code, please review changes once is done
2. There is no way to put paragraphs and also no need for that. We just need to put a few key points into message and that is it. Like `Improving MenuItem props, code cleanup and removing unnecessary comments`. Otherwise, something is wrong and the whole commit has too much different and not connected changes at this point

**Comment by tomothespian** [comment]
@henrylatham also you forgot to run `yarn flow:test`. In case you run that you will see error caused your menu item active/inactive state invalid.

I will fix all issues and then always commit code without `--no-verify` flag to run all tests

**Comment by tomothespian** [comment]
@henrylatham you can check now (last 2 commits)

**Comment by henrylatham** [comment]
@tomothespian Approved

**Pull request merged**
