### PR TITLE
Basic referral system

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces a very first version of referral system integration!

To see ADMIN statistics visit: https://tt-media.hr/public/dashboard

Screen Shot 2019-12-21 at 07 06 49

### CODE REVIEW

**Comment by henrylatham** [comment]
@tomothespian All works really nicely apart from acceptance of referral. See images: 

Screenshot 2020-01-16 at 09 57 05
Screenshot 2020-01-16 at 09 57 10

**Comment by tomothespian** [comment]
@henrylatham did you tested that locally or on live url?

**Comment by henrylatham** [comment]
@tomothespian One issue and one question:

1. Display user email here
Screenshot 2020-01-16 at 11 49 23

2. Is there anything we can do to reduce the chance of an email going to junk mail? 
Screenshot 2020-01-16 at 11 47 57

**Comment by tomothespian** [comment]
@henrylatham 
1. Probably I didn't saw that. I changed the variable name in API and didn't change this. I will fix that
2. I always got email verified, my domain is trusted and also have ssl certificate. We can improve that by using Mailchimp inside API.

**Comment by tomothespian** [comment]
@henrylatham 
1. `Display user email here`: FIXED
2. Email subject fixed
3. Emails SSL checker fixed - mails should not go to spam anymore

I cleared DB so you can test again with the same emails!

**Pull request merged**
